from marshmallow import Schema, fields, validate

class AirtableSourceSchema(Schema):
    source_id = fields.UUID()
    source_name = fields.Str()
    #publication_date = fields.DateTime()
    first_author = fields.Str(validate=validate.Length(max=128))
    url = fields.Str()
    source_type = fields.Str(validate=validate.Length(max=64))
    source_publisher = fields.Str(validate=validate.Length(max=256))
    summary = fields.Str()
    study_type = fields.Str(validate=validate.Length(max=128))
    study_status = fields.Str(validate=validate.Length(max=32))
    country = fields.Str(validate=validate.Length(max=64))
    lead_organization = fields.Str(validate=validate.Length(max=128))
    #sampling_start_date = fields.DateTime()
    #sampling_end_date = fields.DateTime()
    sex = fields.Str(validate=validate.Length(max=16))
    sampling_method = fields.Str(validate=validate.Length(max=128))
    sensitivity = fields.Float()
    specificity = fields.Float()
    include_in_n = fields.Boolean()
    denominator_value = fields.Integer()
    numerator_definition = fields.Str()
    serum_pos_prevalence = fields.Float()
    overall_risk_of_bias = fields.Str(validate=validate.Length(max=128))
    isotype_igg = fields.Boolean()
    isotype_igm = fields.Boolean()
    isotype_iga = fields.Boolean()
    estimate_grade = fields.Str(validate=validate.Length(max=32))
    #created_at = fields.DateTime()
