version: "3"

services:
  app:
    build: .
    restart: always
    image: "iit-backend/app"
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=prod
      - AIRTABLE_API_KEY
      - AIRTABLE_BASE_ID
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_NAME=whiteclaw
      - DATABASE_HOST_ADDRESS
      - MAPBOX_API_KEY
      - LOG_CONFIG_PATH=logging.cfg
      - LOG_FILE_PATH=logfile.log
      - ANALYZE_SPREADSHEET_ID
      - SLACKBOT_TOKEN
