FROM python:3.8.5-slim-buster
WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY . /app
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        make \
        gcc \
        libpq-dev \
        libhdf5-serial-dev \
        netcdf-bin \
        libnetcdf-dev \
        python3-dev \
    && pip install --upgrade pip \
    && pip install psycopg2 \
    && pip install -r requirements.txt \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# set some default environment variables
ENV FLASK_ENV=prod
ENV LOG_CONFIG_PATH=logging.cfg
ENV LOG_FILE_PATH=logfile.log

EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD [ "manage.py", "run"]