"""add country tables

Revision ID: 001ab630a84a
Revises: 2f6fb475355e
Create Date: 2023-06-29 21:19:42.949604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001ab630a84a'
down_revision = '2f6fb475355e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('country_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('country_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_country_bridge_country_id'), 'country_bridge', ['country_id'], unique=False)
    op.create_index(op.f('ix_country_bridge_estimate_id'), 'country_bridge', ['estimate_id'], unique=False)
    op.create_unique_constraint(None, 'state', ['id'])
    op.create_unique_constraint(None, 'state_bridge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state_bridge', type_='unique')
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_index(op.f('ix_country_bridge_estimate_id'), table_name='country_bridge')
    op.drop_index(op.f('ix_country_bridge_country_id'), table_name='country_bridge')
    op.drop_table('country_bridge')
    op.drop_table('country')
    # ### end Alembic commands ###
