"""empty message

Revision ID: 2dd87911d2da
Revises: 7bb264fc54ad
Create Date: 2023-12-06 18:16:21.525159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd87911d2da'
down_revision = '7bb264fc54ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimate', sa.Column('antigen', sa.VARCHAR(length=255), nullable=True), schema='arbo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimate', 'antigen', schema='arbo')
    # ### end Alembic commands ###
