"""add state tables

Revision ID: 2f6fb475355e
Revises: 3a70313b23a8
Create Date: 2023-06-29 21:19:18.309109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f6fb475355e'
down_revision = '3a70313b23a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('state_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('state_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_state_bridge_estimate_id'), 'state_bridge', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_state_bridge_state_id'), 'state_bridge', ['state_id'], unique=False)
    op.create_unique_constraint(None, 'city', ['id'])
    op.create_unique_constraint(None, 'city_bridge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city_bridge', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_index(op.f('ix_state_bridge_state_id'), table_name='state_bridge')
    op.drop_index(op.f('ix_state_bridge_estimate_id'), table_name='state_bridge')
    op.drop_table('state_bridge')
    op.drop_table('state')
    # ### end Alembic commands ###
