"""create anitbody and antibody relationship tables

Revision ID: 377bb16882f2
Revises: ebd0478d1336
Create Date: 2023-06-29 21:14:53.409885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377bb16882f2'
down_revision = 'ebd0478d1336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibody',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('antibody', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('antibody_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('antibody_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibody.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_antibody_bridge_antibody_id'), 'antibody_bridge', ['antibody_id'], unique=False)
    op.create_index(op.f('ix_antibody_bridge_estimate_id'), 'antibody_bridge', ['estimate_id'], unique=False)
    op.create_unique_constraint(None, 'estimates', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimates', type_='unique')
    op.drop_index(op.f('ix_antibody_bridge_estimate_id'), table_name='antibody_bridge')
    op.drop_index(op.f('ix_antibody_bridge_antibody_id'), table_name='antibody_bridge')
    op.drop_table('antibody_bridge')
    op.drop_table('antibody')
    # ### end Alembic commands ###
