"""add city tables

Revision ID: 3a70313b23a8
Revises: d16147756f40
Create Date: 2023-06-29 21:18:46.848993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a70313b23a8'
down_revision = 'd16147756f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('city_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('city_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_city_bridge_city_id'), 'city_bridge', ['city_id'], unique=False)
    op.create_index(op.f('ix_city_bridge_estimate_id'), 'city_bridge', ['estimate_id'], unique=False)
    op.create_unique_constraint(None, 'antigen', ['id'])
    op.create_unique_constraint(None, 'antigen_bridge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'antigen_bridge', type_='unique')
    op.drop_constraint(None, 'antigen', type_='unique')
    op.drop_index(op.f('ix_city_bridge_estimate_id'), table_name='city_bridge')
    op.drop_index(op.f('ix_city_bridge_city_id'), table_name='city_bridge')
    op.drop_table('city_bridge')
    op.drop_table('city')
    # ### end Alembic commands ###
