"""Init Estimates Table

Revision ID: 51e43961f0f4
Revises: 
Create Date: 2023-06-19 21:35:52.575784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e43961f0f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimates',
    sa.Column('estimate_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sex', sa.VARCHAR(length=255), nullable=True),
    sa.Column('age', sa.VARCHAR(length=255), nullable=True),
    sa.Column('antibody', sa.VARCHAR(length=255), nullable=True),
    sa.Column('antigen', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('sample_numerator', sa.Integer(), nullable=True),
    sa.Column('source_sheet', sa.VARCHAR(length=255), nullable=True),
    sa.Column('inclusion_criteria', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pathogen', sa.VARCHAR(length=255), nullable=True),
    sa.Column('seroprevalence', sa.VARCHAR(length=255), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('sample_start_date', sa.Date(), nullable=True),
    sa.Column('sample_end_date', sa.Date(), nullable=True),
    sa.Column('assay', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('estimate_id'),
    sa.UniqueConstraint('estimate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimates')
    # ### end Alembic commands ###
