"""add source sheet tables

Revision ID: 798a3f0577ee
Revises: 001ab630a84a
Create Date: 2023-06-29 21:20:33.698382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '798a3f0577ee'
down_revision = '001ab630a84a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_sheet',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('extractor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('first_author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('source_sheet_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_sheet_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['source_sheet_id'], ['source_sheet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_source_sheet_bridge_estimate_id'), 'source_sheet_bridge', ['estimate_id'], unique=False)
    op.create_index(op.f('ix_source_sheet_bridge_source_sheet_id'), 'source_sheet_bridge', ['source_sheet_id'], unique=False)
    op.create_unique_constraint(None, 'country', ['id'])
    op.create_unique_constraint(None, 'country_bridge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country_bridge', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_index(op.f('ix_source_sheet_bridge_source_sheet_id'), table_name='source_sheet_bridge')
    op.drop_index(op.f('ix_source_sheet_bridge_estimate_id'), table_name='source_sheet_bridge')
    op.drop_table('source_sheet_bridge')
    op.drop_table('source_sheet')
    # ### end Alembic commands ###
