"""Added in WHO region, estimate id and source sheet name

Revision ID: 7bb264fc54ad
Revises: 08ea3c94647c
Create Date: 2023-11-28 19:47:31.610876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb264fc54ad'
down_revision = '08ea3c94647c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'antibody', ['id'], schema='arbo')
    op.create_unique_constraint(None, 'antibody_to_estimate', ['id'], schema='arbo')
    op.create_unique_constraint(None, 'antigen', ['id'], schema='arbo')
    op.create_unique_constraint(None, 'antigen_to_estimate', ['id'], schema='arbo')
    op.add_column('estimate', sa.Column('who_region', sa.VARCHAR(length=5), nullable=True), schema='arbo')
    op.add_column('estimate', sa.Column('estimate_id', sa.VARCHAR(length=255), nullable=True), schema='arbo')
    op.add_column('estimate', sa.Column('source_sheet_name', sa.VARCHAR(length=255), nullable=True), schema='arbo')
    op.create_unique_constraint(None, 'estimate', ['id'], schema='arbo')
    op.create_unique_constraint(None, 'source_sheet', ['id'], schema='arbo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_sheet', schema='arbo', type_='unique')
    op.drop_constraint(None, 'estimate', schema='arbo', type_='unique')
    op.drop_column('estimate', 'source_sheet_name', schema='arbo')
    op.drop_column('estimate', 'estimate_id', schema='arbo')
    op.drop_column('estimate', 'who_region', schema='arbo')
    op.drop_constraint(None, 'antigen_to_estimate', schema='arbo', type_='unique')
    op.drop_constraint(None, 'antigen', schema='arbo', type_='unique')
    op.drop_constraint(None, 'antibody_to_estimate', schema='arbo', type_='unique')
    op.drop_constraint(None, 'antibody', schema='arbo', type_='unique')
    # ### end Alembic commands ###
