"""create antigen and antibody relationship tables

Revision ID: d16147756f40
Revises: 377bb16882f2
Create Date: 2023-06-29 21:16:02.198791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd16147756f40'
down_revision = '377bb16882f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antigen',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('antigen', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('antigen_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('antigen_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['antigen_id'], ['antigen.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_antigen_bridge_antigen_id'), 'antigen_bridge', ['antigen_id'], unique=False)
    op.create_index(op.f('ix_antigen_bridge_estimate_id'), 'antigen_bridge', ['estimate_id'], unique=False)
    op.create_unique_constraint(None, 'antibody', ['id'])
    op.create_unique_constraint(None, 'antibody_bridge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'antibody_bridge', type_='unique')
    op.drop_constraint(None, 'antibody', type_='unique')
    op.drop_index(op.f('ix_antigen_bridge_estimate_id'), table_name='antigen_bridge')
    op.drop_index(op.f('ix_antigen_bridge_antigen_id'), table_name='antigen_bridge')
    op.drop_table('antigen_bridge')
    op.drop_table('antigen')
    # ### end Alembic commands ###
