"""Init estimates table

Revision ID: ebd0478d1336
Revises: 
Create Date: 2023-06-29 21:13:50.842122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebd0478d1336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sex', sa.VARCHAR(length=255), nullable=True),
    sa.Column('age_minimum', sa.Integer(), nullable=True),
    sa.Column('age_maximum', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.VARCHAR(length=255), nullable=True),
    sa.Column('assay_other', sa.VARCHAR(length=255), nullable=True),
    sa.Column('producer', sa.VARCHAR(length=255), nullable=True),
    sa.Column('producer_other', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sample_frame', sa.VARCHAR(length=255), nullable=True),
    sa.Column('same_frame_target_group', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('sample_numerator', sa.Integer(), nullable=True),
    sa.Column('inclusion_criteria', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pathogen', sa.VARCHAR(length=255), nullable=True),
    sa.Column('seroprevalence', sa.VARCHAR(length=255), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('sample_start_date', sa.Date(), nullable=True),
    sa.Column('sample_end_date', sa.Date(), nullable=True),
    sa.Column('assay', sa.VARCHAR(length=255), nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimates')
    # ### end Alembic commands ###
