"""Updated the some varchars to accept larger values

Revision ID: ff898346cda4
Revises: 798a3f0577ee
Create Date: 2023-07-05 18:48:03.059167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff898346cda4'
down_revision = '798a3f0577ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimates', 'inclusion_criteria',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('estimates', 'url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimates', 'url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('estimates', 'inclusion_criteria',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
