dashboard_fields = ['Source Name', 'Publication Date', 'First Author Full Name', 'URL', 'Source Type',
                    'Source Publisher', 'One-Line Summary', 'Study Type', 'Study Status', 'Country',
                    'Lead Organization', 'State/Province', 'County/City', 'Sampling Start Date', 'Sampling End Date',
                    'Sample Frame (sex)', 'Sample Frame (age)', 'Sample Frame (groups of interest)', 'Sampling Method',
                    'Test Manufacturer', 'Approving Regulator', 'Test Type', 'Specimen Type', 'Isotype(s) Reported',
                    'Sensitivity', 'Specificity', 'Include in N?', 'Denominator Value', 'Numerator Definition',
                    'Serum positive prevalence', 'Overall Risk of Bias (JBI)', 'Grade of Estimate Scope']

research_fields = ['Source Name', 'Publication Date', 'First Author Full Name', 'URL', 'Source Type',
                   'Source Publisher', 'One-Line Summary', 'Study Type', 'Study Status', 'Country',
                   'Lead Organization', 'State/Province', 'County/City', 'Sampling Start Date', 'Sampling End Date',
                   'Sample Frame (sex)', 'Sample Frame (age)', 'Sample Frame (groups of interest)', 'Sampling Method',
                   'Test Manufacturer', 'Approving Regulator', 'Test Type', 'Specimen Type', 'Isotype(s) Reported',
                   'Sensitivity', 'Specificity', 'Include in N?', 'Denominator Value', 'Numerator Definition',
                   'Serum positive prevalence', 'Serum + prevalence, 95% CI Lower', 'Serum + prevalence, 95% CI Upper',
                   'Overall Risk of Bias (JBI)', 'Included?', 'Grade of Estimate Scope',
                   'Sub-grouping Variable', 'Geography Type', 'JBI 1', 'JBI 2', 'JBI 3', 'JBI 4', 'JBI 5', 'JBI 6',
                   'JBI 7', 'JBI 8', 'JBI 9', 'Superceded?', 'Test Adjustment', 'Population Adjustment',
                   'Sensitivity Denominator', 'Specificity Denominator', 'Test Validation', 'Independent Se',
                   'Independent Se n', 'Independent Sp', 'Independent Sp n', 'Independent Eval Link',
                   'Independent Eval Lab', 'Average age', 'Measure of age', 'Age variation', 'Age variation measure',
                   'Number of females', 'Number of males', 'Prevalence Estimate Name', 'Rapid Review Study Name (Text)',
                   'Primary Estimate (Text)', 'Notes on Sample Frame']

full_airtable_fields = {
    'Source Name': 'source_name',
    'Publication Date': 'publication_date',
    'First Author Full Name': 'first_author',
    'URL': 'url',
    'Source Type': 'source_type',
    'Source Publisher': 'source_publisher',
    'One-Line Summary': 'summary',
    'Study Type': 'study_type',
    'Grade of Estimate Scope': 'estimate_grade',
    'Study Status': 'study_status',
    'Country': 'country',
    'Lead Organization': 'lead_organization',
    'State/Province': 'state',
    'County/City': 'city',
    'Sampling Start Date': 'sampling_start_date',
    'Sampling End Date': 'sampling_end_date',
    'Sample Frame (sex)': 'sex',
    'Sample Frame (age)': 'age',
    'Sample Frame (groups of interest)': 'population_group',
    'Sampling Method': 'sampling_method',
    'Test Manufacturer': 'test_manufacturer',
    'Approving Regulator': 'approving_regulator',
    'Test Type': 'test_type',
    'Specimen Type': 'specimen_type',
    'Isotype(s) Reported': 'isotypes',
    'Sensitivity': 'sensitivity',
    'Specificity': 'specificity',
    'Include in N?': 'include_in_n',
    'Denominator Value': 'denominator_value',
    'Numerator Definition': 'numerator_definition',
    'Serum positive prevalence': 'serum_pos_prevalence',
    'Serum + prevalence, 95% CI Lower': 'seroprev_95_ci_lower',
    'Serum + prevalence, 95% CI Upper': 'seroprev_95_ci_upper',
    'Overall Risk of Bias (JBI)': 'overall_risk_of_bias',
    'Included?': 'included',
    'Sub-grouping Variable': 'subgroup_var',
    'Geography Type': 'geog_type',
    'JBI 1': 'jbi_1',
    'JBI 2': 'jbi_2',
    'JBI 3': 'jbi_3',
    'JBI 4': 'jbi_4',
    'JBI 5': 'jbi_5',
    'JBI 6': 'jbi_6',
    'JBI 7': 'jbi_7',
    'JBI 8': 'jbi_8',
    'JBI 9': 'jbi_9',
    'Superceded?': 'superceded',
    'Test Adjustment': 'test_adj',
    'Population Adjustment': 'pop_adj',
    'Sensitivity Denominator': 'se_n',
    'Specificity Denominator': 'sp_n',
    'Test Validation': 'test_validation',
    'Independent Se': 'ind_se',
    'Independent Se n': 'ind_se_n',
    'Independent Sp': 'ind_sp',
    'Independent Sp n': 'ind_sp_n',
    'Independent Eval Link': 'ind_eval_link',
    'Independent Eval Lab': 'ind_eval_lab',
    'Average age': 'average_age',
    'Measure of age': 'measure_of_age',
    'Age variation': 'age_variation',
    'Age variation measure': 'age_variation_measure',
    'Number of females': 'number_of_females',
    'Number of males': 'number_of_males',
    'Prevalence Estimate Name': 'estimate_name',
    'Rapid Review Study Name (Text)': 'study_name',
    'Primary Estimate (Text)': 'primary_estimate',
    'Notes on Sample Frame': 'sample_frame_info'}

airtable_fields_config = {'dashboard': {k: full_airtable_fields[k] for k in dashboard_fields},
                          'research': {k: full_airtable_fields[k] for k in research_fields}}
