"""empty message

Revision ID: 05c9c55c0265
Revises: 1e704b229c11
Create Date: 2020-11-28 21:57:08.222508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05c9c55c0265'
down_revision = '1e704b229c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approving_regulator')
    op.drop_table('approving_regulator_bridge')
    op.add_column('airtable_source', sa.Column('approved_by_regulator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'approved_by_regulator')
    op.create_table('approving_regulator_bridge',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('approving_regulator_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='approving_regulator_bridge_pkey')
    )
    op.create_table('approving_regulator',
    sa.Column('approving_regulator_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('approving_regulator_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('approving_regulator_id', name='approving_regulator_pkey')
    )
    # ### end Alembic commands ###
