"""Add population and test adjustment columns

Revision ID: 06974f120ae4
Revises: 53671098a334
Create Date: 2020-11-22 18:37:21.720450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06974f120ae4'
down_revision = '53671098a334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airtable_source', sa.Column('pop_adj', sa.Boolean(), nullable=True))
    op.add_column('airtable_source', sa.Column('test_adj', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'test_adj')
    op.drop_column('airtable_source', 'pop_adj')
    # ### end Alembic commands ###
