"""adding record id column

Revision ID: 0fdd586c6294
Revises: acb8859b0eb8
Create Date: 2021-03-10 21:22:19.581905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdd586c6294'
down_revision = 'acb8859b0eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('record_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'record_id')
    # ### end Alembic commands ###
