"""empty message

Revision ID: 181fa4caafda
Revises: 70bae1ca82e9
Create Date: 2021-05-04 09:28:30.465831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181fa4caafda'
down_revision = '70bae1ca82e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('sensspec_from_manufacturer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'sensspec_from_manufacturer')
    # ### end Alembic commands ###
