"""empty message

Revision ID: 1e704b229c11
Revises: 06974f120ae4
Create Date: 2020-11-28 18:25:28.885978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e704b229c11'
down_revision = '06974f120ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airtable_source', sa.Column('included', sa.Boolean(), nullable=True))
    op.drop_column('airtable_source', 'include_in_n')
    op.drop_column('airtable_source', 'study_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airtable_source', sa.Column('study_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('airtable_source', sa.Column('include_in_n', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('airtable_source', 'included')
    # ### end Alembic commands ###
