"""Add in disputed area column

Revision ID: 262745188771
Revises: 70bae1ca82e9
Create Date: 2021-04-30 13:54:26.971902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262745188771'
down_revision = '70bae1ca82e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('in_disputed_area', sa.Boolean(), nullable=True))
    op.add_column('state', sa.Column('in_disputed_area', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state', 'in_disputed_area')
    op.drop_column('city', 'in_disputed_area')
    # ### end Alembic commands ###
