"""Add county column to research source table

Revision ID: 28f2e9dcdf88
Revises: b5ec83022bdf
Create Date: 2021-06-15 22:16:45.918371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f2e9dcdf88'
down_revision = 'b5ec83022bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('county', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'county')
    # ### end Alembic commands ###
