"""adding alpha3_code and superseder_name cols

Revision ID: 2d8482db23d6
Revises: c49b89f0e274
Create Date: 2022-03-08 14:59:29.808039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8482db23d6'
down_revision = 'c49b89f0e274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('alpha_3_code', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('superseder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'superseder_name')
    op.drop_column('country', 'alpha_3_code')
    # ### end Alembic commands ###
