"""Add latlng and in_disputed_area cols to dashboard source

Revision ID: 527670956fe7
Revises: 93e86260d1eb
Create Date: 2021-05-10 13:00:32.809385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527670956fe7'
down_revision = '93e86260d1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('in_disputed_area', sa.Boolean(), nullable=True))
    op.add_column('dashboard_source', sa.Column('pin_latitude', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('pin_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_source', 'pin_longitude')
    op.drop_column('dashboard_source', 'pin_latitude')
    op.drop_column('dashboard_source', 'in_disputed_area')
    # ### end Alembic commands ###
