"""Add study name column

Revision ID: 53671098a334
Revises: 792dd5bb7d34
Create Date: 2020-11-22 18:20:25.069827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53671098a334'
down_revision = '792dd5bb7d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airtable_source', sa.Column('study_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'study_name')
    # ### end Alembic commands ###
