"""empty message

Revision ID: 56b51bc1e2f0
Revises: 05c9c55c0265
Create Date: 2020-11-28 22:24:26.627461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56b51bc1e2f0'
down_revision = '05c9c55c0265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specimen_type')
    op.drop_table('age_bridge')
    op.drop_table('test_type')
    op.drop_table('specimen_type_bridge')
    op.drop_table('age')
    op.drop_table('test_type_bridge')
    op.add_column('airtable_source', sa.Column('age', sa.String(length=64), nullable=True))
    op.add_column('airtable_source', sa.Column('specimen_type', sa.String(length=64), nullable=True))
    op.add_column('airtable_source', sa.Column('test_type', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'test_type')
    op.drop_column('airtable_source', 'specimen_type')
    op.drop_column('airtable_source', 'age')
    op.create_table('test_type_bridge',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('test_type_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_type_bridge_pkey')
    )
    op.create_table('age',
    sa.Column('age_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('age_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('age_id', name='age_pkey')
    )
    op.create_table('specimen_type_bridge',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('specimen_type_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='specimen_type_bridge_pkey')
    )
    op.create_table('test_type',
    sa.Column('test_type_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_type_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_type_id', name='test_type_pkey')
    )
    op.create_table('age_bridge',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('age_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='age_bridge_pkey')
    )
    op.create_table('specimen_type',
    sa.Column('specimen_type_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('specimen_type_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('specimen_type_id', name='specimen_type_pkey')
    )
    # ### end Alembic commands ###
