"""add mapped etl variables 2020-12-19

Revision ID: 5849f598e66e
Revises: d78fea54bf56
Create Date: 2020-12-19 00:24:35.915862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5849f598e66e'
down_revision = 'd78fea54bf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('gbd_region', sa.String(length=128), nullable=True))
    op.add_column('research_source', sa.Column('gbd_subregion', sa.String(length=128), nullable=True))
    op.add_column('research_source', sa.Column('genpop', sa.String(length=128), nullable=True))
    op.add_column('research_source', sa.Column('lmic_hic', sa.String(length=128), nullable=True))
    op.add_column('research_source', sa.Column('sampling_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'sampling_type')
    op.drop_column('research_source', 'lmic_hic')
    op.drop_column('research_source', 'genpop')
    op.drop_column('research_source', 'gbd_subregion')
    op.drop_column('research_source', 'gbd_region')
    # ### end Alembic commands ###
