"""Add latlng and in_disputed_area cols to dashboard source

Revision ID: 5a06f38194b4
Revises: 70bae1ca82e9
Create Date: 2021-05-01 13:53:21.387375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a06f38194b4'
down_revision = '70bae1ca82e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('in_disputed_area', sa.Boolean(), nullable=True))
    op.add_column('dashboard_source', sa.Column('pin_latitude', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('pin_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_source', 'pin_longitude')
    op.drop_column('dashboard_source', 'pin_latitude')
    op.drop_column('dashboard_source', 'in_disputed_area')
    # ### end Alembic commands ###
