"""Ingest OWID data

Revision ID: 768541e19c09
Revises: ca6774a83788
Create Date: 2021-02-17 22:27:24.339468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768541e19c09'
down_revision = 'ca6774a83788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('case_count', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('death_count', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('full_vaccination_count', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('test_count', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('vaccination_count', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_source', 'vaccination_count')
    op.drop_column('dashboard_source', 'test_count')
    op.drop_column('dashboard_source', 'full_vaccination_count')
    op.drop_column('dashboard_source', 'death_count')
    op.drop_column('dashboard_source', 'case_count')
    # ### end Alembic commands ###
