"""add columns for estimate prioritization

Revision ID: 792dd5bb7d34
Revises: 53623d4c86d4
Create Date: 2020-11-22 17:15:08.554729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792dd5bb7d34'
down_revision = '53623d4c86d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airtable_source', sa.Column('academic_primary_estimate', sa.Boolean(), nullable=True))
    op.add_column('airtable_source', sa.Column('dashboard_primary_estimate', sa.Boolean(), nullable=True))
    op.add_column('airtable_source', sa.Column('isotype_comb', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'isotype_comb')
    op.drop_column('airtable_source', 'dashboard_primary_estimate')
    op.drop_column('airtable_source', 'academic_primary_estimate')
    # ### end Alembic commands ###
