"""add_country_iso3_col_2020-12-25

Revision ID: 818a6b452459
Revises: 8d7970c8822f
Create Date: 2020-12-15 19:49:38.759199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818a6b452459'
down_revision = '8d7970c8822f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('country_iso3', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'country_iso3')
    # ### end Alembic commands ###
