"""remove_ind_se_and_ind_sp_columns_2023_07_31

Revision ID: 8a5bebf51613
Revises: d002b0434489
Create Date: 2023-07-31 17:15:01.366975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a5bebf51613'
down_revision = 'd002b0434489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_source', schema=None) as batch_op:
        batch_op.drop_column('ind_sp')
        batch_op.drop_column('ind_sp_n')
        batch_op.drop_column('ind_se')
        batch_op.drop_column('ind_eval_link')
        batch_op.drop_column('ind_se_n')
        batch_op.drop_column('ind_eval_lab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ind_eval_lab', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ind_se_n', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ind_eval_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ind_se', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ind_sp_n', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ind_sp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
