"""Adding created at col to research source

Revision ID: 8d7970c8822f
Revises: 9648101bbd7a
Create Date: 2020-12-13 22:53:07.063114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7970c8822f'
down_revision = '9648101bbd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'created_at')
    # ### end Alembic commands ###
