"""adding created at column to research table 2021-01-15

Revision ID: 91e8600aac0d
Revises: de214a6b9ebd
Create Date: 2021-01-15 17:27:20.564053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e8600aac0d'
down_revision = 'de214a6b9ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'created_at')
    # ### end Alembic commands ###
