"""add_income_hrp_class_cols

Revision ID: 93e86260d1eb
Revises: 3d3b45cb6ce4
Create Date: 2021-05-07 13:28:50.771641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e86260d1eb'
down_revision = '3d3b45cb6ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('hrp_class', sa.String(), nullable=True))
    op.add_column('country', sa.Column('income_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'income_class')
    op.drop_column('country', 'hrp_class')
    # ### end Alembic commands ###
