"""Adding research source table

Revision ID: 9648101bbd7a
Revises: aeb30d1316ca
Create Date: 2020-12-13 16:14:51.399387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9648101bbd7a'
down_revision = 'aeb30d1316ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibody_target',
    sa.Column('antibody_target_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('antibody_target_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('antibody_target_id')
    )
    op.create_table('antibody_target_bridge',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('antibody_target_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_source',
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('first_author', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_publisher', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('study_name', sa.String(), nullable=True),
    sa.Column('study_type', sa.String(length=128), nullable=True),
    sa.Column('country_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('lead_organization', sa.String(length=128), nullable=True),
    sa.Column('sampling_start_date', sa.DateTime(), nullable=True),
    sa.Column('sampling_end_date', sa.DateTime(), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('population_group', sa.String(length=128), nullable=True),
    sa.Column('sampling_method', sa.String(length=128), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('specificity', sa.Float(), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.Column('denominator_value', sa.Integer(), nullable=True),
    sa.Column('numerator_definition', sa.String(), nullable=True),
    sa.Column('serum_pos_prevalence', sa.Float(), nullable=True),
    sa.Column('overall_risk_of_bias', sa.String(length=16), nullable=True),
    sa.Column('isotype_igg', sa.Boolean(), nullable=True),
    sa.Column('isotype_igm', sa.Boolean(), nullable=True),
    sa.Column('isotype_iga', sa.Boolean(), nullable=True),
    sa.Column('specimen_type', sa.String(length=64), nullable=True),
    sa.Column('estimate_grade', sa.String(length=32), nullable=True),
    sa.Column('academic_primary_estimate', sa.Boolean(), nullable=True),
    sa.Column('dashboard_primary_estimate', sa.Boolean(), nullable=True),
    sa.Column('isotype_comb', sa.String(length=32), nullable=True),
    sa.Column('test_type', sa.String(length=256), nullable=True),
    sa.Column('test_adj', sa.Boolean(), nullable=True),
    sa.Column('pop_adj', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('research_source',
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('case_population', sa.Integer(), nullable=True),
    sa.Column('deaths_population', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Float(), nullable=True),
    sa.Column('age_min', sa.Float(), nullable=True),
    sa.Column('age_variation', sa.String(length=128), nullable=True),
    sa.Column('age_variation_measure', sa.String(length=64), nullable=True),
    sa.Column('average_age', sa.String(length=256), nullable=True),
    sa.Column('case_count_neg14', sa.Integer(), nullable=True),
    sa.Column('case_count_neg9', sa.Integer(), nullable=True),
    sa.Column('case_count_0', sa.Integer(), nullable=True),
    sa.Column('death_count_plus11', sa.Integer(), nullable=True),
    sa.Column('death_count_plus4', sa.Integer(), nullable=True),
    sa.Column('ind_eval_lab', sa.String(length=128), nullable=True),
    sa.Column('ind_eval_link', sa.String(), nullable=True),
    sa.Column('ind_se', sa.Float(), nullable=True),
    sa.Column('ind_se_n', sa.Float(), nullable=True),
    sa.Column('ind_sp', sa.Float(), nullable=True),
    sa.Column('ind_sp_n', sa.Float(), nullable=True),
    sa.Column('jbi_1', sa.String(length=16), nullable=True),
    sa.Column('jbi_2', sa.String(length=16), nullable=True),
    sa.Column('jbi_3', sa.String(length=16), nullable=True),
    sa.Column('jbi_4', sa.String(length=16), nullable=True),
    sa.Column('jbi_5', sa.String(length=16), nullable=True),
    sa.Column('jbi_6', sa.String(length=16), nullable=True),
    sa.Column('jbi_7', sa.String(length=16), nullable=True),
    sa.Column('jbi_8', sa.String(length=16), nullable=True),
    sa.Column('jbi_9', sa.String(length=16), nullable=True),
    sa.Column('measure_of_age', sa.String(length=64), nullable=True),
    sa.Column('sample_frame_info', sa.String(), nullable=True),
    sa.Column('number_of_females', sa.Integer(), nullable=True),
    sa.Column('number_of_males', sa.Integer(), nullable=True),
    sa.Column('numerator_value', sa.Float(), nullable=True),
    sa.Column('estimate_name', sa.String(), nullable=True),
    sa.Column('test_not_linked_reason', sa.String(), nullable=True),
    sa.Column('se_n', sa.Float(), nullable=True),
    sa.Column('seroprev_95_ci_lower', sa.Float(), nullable=True),
    sa.Column('seroprev_95_ci_upper', sa.Float(), nullable=True),
    sa.Column('sp_n', sa.Float(), nullable=True),
    sa.Column('subgroup_var', sa.String(length=128), nullable=True),
    sa.Column('subgroup_cat', sa.String(length=128), nullable=True),
    sa.Column('superceded', sa.Boolean(), nullable=True),
    sa.Column('test_linked_uid', sa.String(), nullable=True),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.Column('test_validation', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.drop_table('airtable_source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airtable_source',
    sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_author', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source_publisher', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('study_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('lead_organization', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('sampling_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sampling_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('sampling_method', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('sensitivity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('specificity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('denominator_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numerator_definition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('serum_pos_prevalence', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_risk_of_bias', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('isotype_igg', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isotype_igm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isotype_iga', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('estimate_grade', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('country_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('academic_primary_estimate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dashboard_primary_estimate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isotype_comb', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('study_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pop_adj', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('test_adj', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('included', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('specimen_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('test_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('population_group', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_id', name='airtable_source_pkey')
    )
    op.drop_table('research_source')
    op.drop_table('dashboard_source')
    op.drop_table('antibody_target_bridge')
    op.drop_table('antibody_target')
    # ### end Alembic commands ###
