"""add_manufacturer_columns_to_dashboard_source_2023_08_3

Revision ID: a7da3dbefaf3
Revises: 8a5bebf51613
Create Date: 2023-08-03 17:54:11.562275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7da3dbefaf3'
down_revision = '8a5bebf51613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer_sensitivity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('manufacturer_specificity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_source', schema=None) as batch_op:
        batch_op.drop_column('manufacturer_specificity')
        batch_op.drop_column('manufacturer_sensitivity')

    # ### end Alembic commands ###
