"""Move subgroup_var to dashboard_source table

Revision ID: ab3821bad767
Revises: 527670956fe7
Create Date: 2021-05-13 16:56:18.574744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3821bad767'
down_revision = '527670956fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('subgroup_var', sa.String(), nullable=True))
    op.drop_column('research_source', 'subgroup_var')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('subgroup_var', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dashboard_source', 'subgroup_var')
    # ### end Alembic commands ###
