"""Add verbose column names, add geo exact match

Revision ID: acb8859b0eb8
Revises: 768541e19c09
Create Date: 2021-03-06 13:41:01.162974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acb8859b0eb8'
down_revision = '637c0739c860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('cases_per_hundred', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('deaths_per_hundred', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('full_vaccinations_per_hundred', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('geo_exact_match', sa.Boolean(), nullable=True))
    op.add_column('dashboard_source', sa.Column('tests_per_hundred', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('vaccinations_per_hundred', sa.Float(), nullable=True))
    op.drop_column('dashboard_source', 'death_count')
    op.drop_column('dashboard_source', 'test_count')
    op.drop_column('dashboard_source', 'case_count')
    op.drop_column('dashboard_source', 'vaccination_count')
    op.drop_column('dashboard_source', 'full_vaccination_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('full_vaccination_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dashboard_source', sa.Column('vaccination_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dashboard_source', sa.Column('case_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dashboard_source', sa.Column('test_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dashboard_source', sa.Column('death_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('dashboard_source', 'vaccinations_per_hundred')
    op.drop_column('dashboard_source', 'tests_per_hundred')
    op.drop_column('dashboard_source', 'geo_exact_match')
    op.drop_column('dashboard_source', 'full_vaccinations_per_hundred')
    op.drop_column('dashboard_source', 'deaths_per_hundred')
    op.drop_column('dashboard_source', 'cases_per_hundred')
    # ### end Alembic commands ###
