"""removing superceded column

Revision ID: ad224cf5bd53
Revises: f85fec82f462
Create Date: 2021-04-07 22:31:02.513687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad224cf5bd53'
down_revision = 'f85fec82f462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'superceded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('superceded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
