"""delete approving regulator col

Revision ID: aeb30d1316ca
Revises: af9a59693583
Create Date: 2020-12-03 19:21:48.138264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb30d1316ca'
down_revision = 'af9a59693583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'approved_by_regulator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airtable_source', sa.Column('approved_by_regulator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
