"""delete population group table

Revision ID: af9a59693583
Revises: 56b51bc1e2f0
Create Date: 2020-11-29 12:04:06.926405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af9a59693583'
down_revision = '56b51bc1e2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('population_group')
    op.drop_table('population_group_bridge')
    op.add_column('airtable_source', sa.Column('population_group', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airtable_source', 'population_group')
    op.create_table('population_group_bridge',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('population_group_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='population_group_bridge_pkey')
    )
    op.create_table('population_group',
    sa.Column('population_group_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('population_group_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('population_group_id', name='population_group_pkey')
    )
    # ### end Alembic commands ###
