"""Add some supplementary columns for the location tables

Revision ID: b5ec83022bdf
Revises: c42f2f28612b
Create Date: 2021-06-11 16:11:29.280728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ec83022bdf'
down_revision = 'c42f2f28612b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country_iso2', sa.String(), nullable=True))
    op.add_column('country', sa.Column('country_iso2', sa.String(), nullable=True))
    op.add_column('state', sa.Column('country_iso2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state', 'country_iso2')
    op.drop_column('country', 'country_iso2')
    op.drop_column('city', 'country_iso2')
    # ### end Alembic commands ###
