"""changing research source fields

Revision ID: c39af184fa8b
Revises: 176da0a27daf
Create Date: 2021-11-03 22:07:59.751749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39af184fa8b'
down_revision = '176da0a27daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('jbi_a_outputs_v5', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('multiple_test_gold_standard_algorithm', sa.String(), nullable=True))
    op.drop_column('research_source', 'test_linked_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('test_linked_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('research_source', 'multiple_test_gold_standard_algorithm')
    op.drop_column('research_source', 'jbi_a_outputs_v5')
    # ### end Alembic commands ###
