"""Add unity aligned column

Revision ID: c42f2f28612b
Revises: 6d154dc9fa83
Create Date: 2021-06-07 09:40:32.934598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42f2f28612b'
down_revision = '6d154dc9fa83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('is_unity_aligned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_source', 'is_unity_aligned')
    # ### end Alembic commands ###
