"""add_german_col_to_popgroup_options

Revision ID: c49b89f0e274
Revises: cdbb3ba85912
Create Date: 2021-12-18 09:47:33.251477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49b89f0e274'
down_revision = 'cdbb3ba85912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('population_group_options', sa.Column('german_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('population_group_options', 'german_name')
    # ### end Alembic commands ###
