"""Add exact geo match flag

Revision ID: c66d4202ea9c
Revises: 768541e19c09
Create Date: 2021-03-04 00:16:07.558626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d4202ea9c'
down_revision = '768541e19c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('geo_exact_match', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_source', 'geo_exact_match')
    # ### end Alembic commands ###
