"""adding research source columns without string length limits

Revision ID: ca6774a83788
Revises: 658789067e43
Create Date: 2021-01-31 19:26:30.759495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6774a83788'
down_revision = '658789067e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('age_variation', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('age_variation_measure', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('average_age', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('gbd_region', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('gbd_subregion', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('genpop', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('ind_eval_lab', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_1', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_2', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_3', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_4', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_5', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_6', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_7', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_8', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('jbi_9', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('lmic_hic', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('measure_of_age', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('sampling_type', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('subgroup_cat', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('subgroup_specific_category', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('subgroup_var', sa.String(), nullable=True))
    op.add_column('research_source', sa.Column('test_validation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'test_validation')
    op.drop_column('research_source', 'subgroup_var')
    op.drop_column('research_source', 'subgroup_specific_category')
    op.drop_column('research_source', 'subgroup_cat')
    op.drop_column('research_source', 'sampling_type')
    op.drop_column('research_source', 'measure_of_age')
    op.drop_column('research_source', 'lmic_hic')
    op.drop_column('research_source', 'jbi_9')
    op.drop_column('research_source', 'jbi_8')
    op.drop_column('research_source', 'jbi_7')
    op.drop_column('research_source', 'jbi_6')
    op.drop_column('research_source', 'jbi_5')
    op.drop_column('research_source', 'jbi_4')
    op.drop_column('research_source', 'jbi_3')
    op.drop_column('research_source', 'jbi_2')
    op.drop_column('research_source', 'jbi_1')
    op.drop_column('research_source', 'ind_eval_lab')
    op.drop_column('research_source', 'genpop')
    op.drop_column('research_source', 'gbd_subregion')
    op.drop_column('research_source', 'gbd_region')
    op.drop_column('research_source', 'average_age')
    op.drop_column('research_source', 'age_variation_measure')
    op.drop_column('research_source', 'age_variation')
    # ### end Alembic commands ###
