"""adding immunoassays col

Revision ID: cdbb3ba85912
Revises: c39af184fa8b
Create Date: 2021-12-01 22:50:12.898510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbb3ba85912'
down_revision = 'c39af184fa8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('immunoassays_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'immunoassays_name')
    # ### end Alembic commands ###
