"""adding study_exclusion_criteria to research source

Revision ID: d002b0434489
Revises: 2d8482db23d6
Create Date: 2022-03-22 23:26:02.026442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd002b0434489'
down_revision = '2d8482db23d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('study_exclusion_criteria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'study_exclusion_criteria')
    # ### end Alembic commands ###
