"""Move gbd region column to dashboard source table

Revision ID: d74edc1a135f
Revises: ca6774a83788
Create Date: 2021-02-03 21:45:57.146904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74edc1a135f'
down_revision = 'ca6774a83788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('gbd_region', sa.String(), nullable=True))
    op.drop_column('research_source', 'gbd_region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('gbd_region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dashboard_source', 'gbd_region')
    # ### end Alembic commands ###
