"""Add state_name column to city table 2020-12-18

Revision ID: d78fea54bf56
Revises: 818a6b452459
Create Date: 2020-12-18 17:09:46.596798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78fea54bf56'
down_revision = '818a6b452459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('state_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'state_name')
    # ### end Alembic commands ###
