"""add zotero_citation_key field

Revision ID: f84604f8c5f7
Revises: 181fa4caafda
Create Date: 2021-05-14 11:24:47.232295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84604f8c5f7'
down_revision = '181fa4caafda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('zotero_citation_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'zotero_citation_key')
    # ### end Alembic commands ###
