"""adding test adjustment output columns

Revision ID: f85fec82f462
Revises: ae628d37e6de
Create Date: 2021-03-20 16:00:23.661395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85fec82f462'
down_revision = 'ae628d37e6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_source', sa.Column('adj_prev_ci_lower', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('adj_prev_ci_upper', sa.Float(), nullable=True))
    op.add_column('dashboard_source', sa.Column('adj_prevalence', sa.Float(), nullable=True))
    op.add_column('research_source', sa.Column('adj_sensitivity', sa.Float(), nullable=True))
    op.add_column('research_source', sa.Column('adj_specificity', sa.Float(), nullable=True))
    op.add_column('research_source', sa.Column('ind_eval_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'ind_eval_type')
    op.drop_column('research_source', 'adj_specificity')
    op.drop_column('research_source', 'adj_sensitivity')
    op.drop_column('dashboard_source', 'adj_prevalence')
    op.drop_column('dashboard_source', 'adj_prev_ci_upper')
    op.drop_column('dashboard_source', 'adj_prev_ci_lower')
    # ### end Alembic commands ###
