"""Add include in SRMA column

Revision ID: fe611d0aed1c
Revises: ad224cf5bd53
Create Date: 2021-04-09 00:13:22.776756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe611d0aed1c'
down_revision = 'ad224cf5bd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_source', sa.Column('include_in_srma', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_source', 'include_in_srma')
    # ### end Alembic commands ###
