name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.3'
    - name: Install
      run: |
        pip install -r requirements.txt
        mkdir data/
        curl "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv" > data/vaccinations.csv
        curl "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/testing/covid-testing-all-observations.csv" > data/tests.csv
        curl "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/total_deaths_per_million.csv" > data/deaths.csv
        curl "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/total_cases_per_million.csv" > data/cases.csv
    - name: Test
      run: |
        python manage.py test
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        FLASK_ENV: 'test'
        LOG_CONFIG_PATH: '/home/runner/work/iit-backend/iit-backend/logging.cfg'
        LOG_FILE_PATH: '/home/runner/work/iit-backend/iit-backend/logfile.log'
        CSV_DIR: 'data/'
