name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
        postgresql db: 'whiteclaw_test'
        postgresql user: 'postgres'
        postgresql password: 'postgres'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.3'
    - name: Install
      run: |
        pip install -r requirements.txt
    - name: Test
      run: |
        pytest -vv
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        FLASK_ENV: 'test'
        LOG_CONFIG_PATH: '/home/runner/work/iit-backend/iit-backend/logging.cfg'
        LOG_FILE_PATH: '/home/runner/work/iit-backend/iit-backend/logfile.log'
