name: Deploy EB Prod

on:
  push:
    branches:
      - eb-github-actions
  repository_dispatch:
    types: manual-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: serotracker/iit-backend:latest
        file: Dockerfile-app
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.3'
    - name: Install aws eb cli
      run: |
        pip install awsebcli