
name: Push CSV to Repo

on:
  workflow_dispatch: # manual trigger 
  push:
    branches:
      - prannoy/workflow-setup
  # schedule:
  #   - cron: '0 12 * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install python packages
        run: |
          pip install -r requirements.txt
      # - name: Execute py script # run estimate_csv_creator.py to get CSV
      #   run: python3 app/github_public_repo/estimate_csv_creator.py
      # - name: Copy CSV
      #   uses: andstor/copycat-action@v3
      #   with:
      #     personal_token: ${{ secrets.API_TOKEN_GITHUB }}
      #     src_path: /output/.
      #     dst_path: /
      #     exclude: "*.py"
      #     dst_owner: serotracker
      #     dst_repo_name: sars-cov-2-data
      #     dst_branch: test
      #     src_branch: simona/github_csv_driver_script
      #     src_wiki: false
      #     dst_wiki: false
      #     username: serosurveillance-can
      #     email: can.serosurveillance.dev@gmail.com
     
     

