
name: Push CSV to Repo

on:
  workflow_dispatch: # manual trigger 
  push:
    branches:
      - prannoy/workflow-setup
  # schedule:
  #   - cron: '0 12 * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install packages
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: Create CSV locally  # run estimate_csv_creator.py to get CSV
        run: python3 /home/runner/work/iit-backend/iit-backend/app/github_public_repo/estimate_csv_creator.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          FLASK_ENV: 'dev'
          LOG_CONFIG_PATH: '/home/runner/work/iit-backend/iit-backend/logging.cfg'
          LOG_FILE_PATH: '/home/runner/work/iit-backend/iit-backend/logfile.log'
          PYTHONPATH: '/home/runner/work/iit-backend/iit-backend'
      - name: Commit updated CSV 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updated serotracker_dataset.csv
          branch: main
          repository: /home/runner/work/iit-backend/iit-backend/app/github_public_repo/
          commit_user_name: serosurveillance-can 
          commit_user_email: can.serosurveillance.dev@gmail.com # defaults to "actions@github.com"
          commit_author: serosurveillance-can <can.serosurveillance.dev@gmail.com> # defaults to author of the commit that triggered the run
          status_options: '--untracked-files=no'
      - name: Copy CSV
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: app/github_public_repo/.
          dst_path: / 
          exclude: "*.py"
          dst_owner: serotracker
          dst_repo_name: sars-cov-2-data
          dst_branch: main
          src_branch: master
          src_wiki: false
          dst_wiki: false
          username: serosurveillance-can
          email: can.serosurveillance.dev@gmail.com
     
     

