name: Push GitHub CSV to Repo

on:
  workflow_dispatch: # manual trigger 
  schedule:
    - cron: '30 14 * * *' # runs at 2:30 PM UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout iit-backend
        uses: actions/checkout@v2
        with:
          path: iit-backend

      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.8.3' #install the python needed
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arcgis==1.3.0
          pip install -r iit-backend/requirements.txt
          pip install git+https://github.com/stan-dev/pystan2.git@master
          
         
#       - name: Install packages
#         uses: BSFishy/pip-action@v1
#         with:
#           requirements: iit-backend/requirements.txt
  
      - name: Create CSV locally  # run estimate_csv_creator.py to get CSV
        run: python3 $GITHUB_WORKSPACE/iit-backend/app/github_public_repo/estimate_csv_creator.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          FLASK_ENV: 'dev'
          LOG_CONFIG_PATH: 'iit-backend/logging.cfg'
          LOG_FILE_PATH: 'iit-backend/logfile.log'
          PYTHONPATH: 'iit-backend'
          CSV_TYPE: 'github'
    
      - name: Copies and pushes CSV to sars-cov-2-data (main branch)
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '/home/runner/work/iit-backend/iit-backend/serotracker_dataset.csv'
          destination_repo: 'serotracker/sars-cov-2-data'
          user_email: 'can.serosurveillance.dev@gmail.com'
          user_name: 'serosurveillance-can '
          commit_message: 'Updated serotracker_dataset.csv'


     

