
name: Push CSV to Repo

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Copy CSV
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: /output/.
          dst_path: /
          exclude: "*.py"
          dst_owner: serotracker
          dst_repo_name: sars-cov-2-data
          dst_branch: main
          src_branch: master
          src_wiki: false
          dst_wiki: false
          username: annoyingpr
          email: prannoylal@gmail.com
     
     

